// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrRZlCcZPBrnYju1bSvMJF_bDIHOSK2Y',
    appId: '1:182478109040:web:336cdcaedcc3f5eac3b7b5',
    messagingSenderId: '182478109040',
    projectId: 'bulbcontroller-33731',
    authDomain: 'bulbcontroller-33731.firebaseapp.com',
    databaseURL: 'https://bulbcontroller-33731-default-rtdb.firebaseio.com',
    storageBucket: 'bulbcontroller-33731.firebasestorage.app',
    measurementId: 'G-GEZ0M1SQJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nrGccu2mEP87ahh0XVMrnWutj69KPQw',
    appId: '1:182478109040:android:0bbb73b9e69bde12c3b7b5',
    messagingSenderId: '182478109040',
    projectId: 'bulbcontroller-33731',
    databaseURL: 'https://bulbcontroller-33731-default-rtdb.firebaseio.com',
    storageBucket: 'bulbcontroller-33731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFULlCypyVGsiu-qfGBGxdLgJLnjZDaao',
    appId: '1:182478109040:ios:f6f667a5169869ffc3b7b5',
    messagingSenderId: '182478109040',
    projectId: 'bulbcontroller-33731',
    databaseURL: 'https://bulbcontroller-33731-default-rtdb.firebaseio.com',
    storageBucket: 'bulbcontroller-33731.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFULlCypyVGsiu-qfGBGxdLgJLnjZDaao',
    appId: '1:182478109040:ios:f6f667a5169869ffc3b7b5',
    messagingSenderId: '182478109040',
    projectId: 'bulbcontroller-33731',
    databaseURL: 'https://bulbcontroller-33731-default-rtdb.firebaseio.com',
    storageBucket: 'bulbcontroller-33731.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHrRZlCcZPBrnYju1bSvMJF_bDIHOSK2Y',
    appId: '1:182478109040:web:55ac2835d203b1a1c3b7b5',
    messagingSenderId: '182478109040',
    projectId: 'bulbcontroller-33731',
    authDomain: 'bulbcontroller-33731.firebaseapp.com',
    databaseURL: 'https://bulbcontroller-33731-default-rtdb.firebaseio.com',
    storageBucket: 'bulbcontroller-33731.firebasestorage.app',
    measurementId: 'G-4LHV9MDKTE',
  );
}
